# Generated by Django 4.2.2 on 2023-06-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastTested',
            new_name='last_tested',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
