# Generated by Django 4.2.2 on 2023-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_createdat_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Active', max_length=200),
            preserve_default=False,
        ),
    ]
